In [4]:
import pandas as pd
from pymongo import MongoClient
import json
pd.set_option('display.max_columns', None)

In [2]:
FILE_PATH = "../data/houses-for-rent.csv"
ATLAS_URL = "mongodb+srv://conghuynt1999:foWcElkNDeLlDNIX@cluster1.oq1l7.mongodb.net/?retryWrites=false&replicaSet=atlas-5tjaoq-shard-0"
DATABASE_NAME = "chotot"
COLLECTION_NAME = "raw_houses_for_rent"

In [5]:
houses_df = pd.read_csv(FILE_PATH)
houses_df.head()

,ad_id,list_id,list_time,subject,body,price,price_string,size,rooms,toilets,area_name,region_name,ward_name,street_name,deposit,zero_deposit,longitude,latitude,owner,company_ad,apartment_type
0,148983771,109051906,1702006245000,"1 PHÒNG NGỦ TÁCH BẾP 45M2, CHO NUÔI PET!",CĂN HỘ CAO CẤP 1 PHÒNG NGỦ!__45M2\n✓BAN CÔNG L...,8600000,"8,6 triệu/tháng",45.0,1,1.0,Thành phố Thủ Đức,Tp Hồ Chí Minh,Phường Thảo Điền (Quận 2 cũ),Nguyễn Văn Hưởng,8600000,False,106.72764,10.815886,False,True,"Căn hộ dịch vụ, mini"
1,152808559,112328722,1701933976000,Căn hộ chung cư saigonLAND hẻm 69 Nguyễn Gia T...,Cần cho thuê căn chung cư Saigon Land tại hẻm ...,15000000,15 triệu/tháng,110.0,3,2.0,Quận Bình Thạnh,Tp Hồ Chí Minh,Phường 25,D2,0,False,106.71600,10.805900,False,False,Chung cư
2,152043174,111673373,1702110778000,LAVITA CHARM CHO THUÊ CH 2PN 68M2 CÓ NT ĐẸP,CH LAVITA CHARM 1PN VIEW ĐẸP NGAY GẦN NGÃ TƯ B...,8500000,"8,5 triệu/tháng",68.0,2,2.0,Thành phố Thủ Đức,Tp Hồ Chí Minh,Phường Trường Thọ (Quận Thủ Đức cũ),Số 1,0,False,106.75830,10.826700,False,True,Chung cư
3,150969082,110755872,1701743146000,CH cửa kính Thoáng Mát - Máy giặt riêng Ngay Đ...,CH cửa kính Thoáng Mát - Máy giặt riêng Ngay Đ...,7000000,7 triệu/tháng,35.0,1,1.0,Quận 5,Tp Hồ Chí Minh,Phường 4,Đường Trần Phú,0,False,106.67910,10.762500,False,True,Chung cư
4,150055631,109969444,1702115497000,Chính chủ Cho thuê căn hộ Saigon South căn 2PN...,"- Căn hộ 71m², 75m², 76m² - 2PN + 2WC.\n+ Nội ...",13000000,13 triệu/tháng,75.0,2,2.0,Huyện Nhà Bè,Tp Hồ Chí Minh,Xã Phước Kiển,Nguyễn Hữu Thọ,0,False,106.71276,10.703870,False,True,Chung cư

In [6]:
houses_df.dtypes

ad_id               int64
list_id             int64
list_time           int64
subject            object
body               object
price               int64
price_string       object
size              float64
rooms               int64
toilets           float64
area_name          object
region_name        object
ward_name          object
street_name        object
deposit             int64
zero_deposit         bool
longitude         float64
latitude          float64
owner                bool
company_ad           bool
apartment_type     object
dtype: object

In [7]:
db = MongoClient(ATLAS_URL)[DATABASE_NAME]
# !WARNING: drop collection then create new one
if COLLECTION_NAME in db.list_collection_names():
    db[COLLECTION_NAME].drop()
db.create_collection(
    COLLECTION_NAME,
    validator={
        "$jsonSchema": {
            "bsonType": "object",
            "additionalProperties": True,
            "properties": {
                "ad_id": {"bsonType": "long"},
                "list_id":{"bsonType": "long"},
                "list_time": {"bsonType": "long"},
                "subject": {"bsonType": "string"},
                "body": {"bsonType": "string"},
                "price": {"bsonType": "long"},
                "price_string": {"bsonType": "string"},
                "size": {"bsonType": "double"},
                "rooms": {"bsonType": "int"},
                "toilets": {"bsonType": "double"},
                "area_name": {"bsonType": "string"},
                "region_name": {"bsonType": "string"},
                "street_name": {"bsonType": "string"},
                "deposit": {"bsonType": "long"},
                "zero_deposit": {"bsonType": "bool"},
                "longitude": {"bsonType": "double"},
                "latitude": {"bsonType": "double"},
                "owner": {"bsonType": "bool"},
                "company_ad": {"bsonType": "bool"},
                "apartment_type": {"bsonType": "string"}
            },
        }
    },
)

Collection(Database(MongoClient(host=['cluster1-shard-00-00.oq1l7.mongodb.net:27017', 'cluster1-shard-00-02.oq1l7.mongodb.net:27017', 'cluster1-shard-00-01.oq1l7.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=False, replicaset='atlas-5tjaoq-shard-0', authsource='admin', tls=True), 'chotot'), 'raw_houses_for_rent')

In [ ]:
# db.get_collection(COLLECTION_NAME).insert_many()
# list(db.get_collection("jobs").find().limit(5))